try:
	print(x)
except:
	print("An exception occured")